version: 2

sources:
  - name: studentdata
    description: '{{ doc("table_events") }}'
    #database: studentdata
    schema: studentdata
    tables:
      - name: std
        columns:
          - name: SNO
            tests:
              - unique
              - not_null
            test:
              - is_studentdata
